FROM n8nio/n8n

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=changeme
ENV DB_TYPE=sqlite
ENV N8N_HOST=n8n.onrender.com
ENV WEBHOOK_TUNNEL_URL=https://n8n.onrender.com
